name: MineXON
version: '${project.version}'
main: net.minexon.minexon.MineXON
api-version: 1.13
depend: [ hCore ]
softdepend: [ PlaceholderAPI ]
authors: [ zRooter ]
description: made by zRooter with love
website: https://minexon.net
